<?php

/**
 * @file
 * Contains 'zopim' module hooks.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\zopim\Form\SettingsForm;

/**
 * Implements hook_help().
 */
function zopim_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.zopim':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module provides an integration for <a href=":zopim-url">Zopim live-chat</a> service.', [':zopim-url' => 'https://zopim.com/?lang=en']) . '</p>';

      return $output;
  }
}

/**
 * Implements hook_rebuild().
 */
function zopim_rebuild() {
  $config_factory = \Drupal::configFactory();
  $js_collection = \Drupal::service('asset.js.collection_optimizer');
  $tags_invalidator = \Drupal::service('cache_tags.invalidator');
  $form = new SettingsForm($config_factory, $js_collection, $tags_invalidator);
  $form->createAssets();
}
