zopim.settings:
  type: config_object
  label: 'Zopim Chat settings'
  mapping:
    integration:
      type: string
      label: 'Integration type'
    zopim_account:
      type: string
      label: 'Zopim account'
    zendesk_hostname:
      type: string
      label: 'Zendesk hostname'
    embed:
      type: text_format
      label: 'Embed script'